# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provision :shell, inline: "echo VM Criada com sucesso!"

  config.vm.define :files do |srvfile|
    config.vm.provider "virtualbox" do |vb|
      vb.memory = 512
      vb.cpus = 1
      vb.name = "SRV-FILE"
    end
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "SRV-FILE"
  config.vm.synced_folder 'C:\Users\Lucas\Documents\FileSync\share', '/home/share/', disabled: true
  end
  
  config.vm.define :client01 do |client01|
    config.vm.provider "virtualbox" do |vb|
      vb.memory = 256
      vb.cpus = 1
      vb.name = "CLIENT01"
      vb.linked_clone = true
    end
  config.vm.hostname = "CLIENT01"
  config.vm.synced_folder 'C:\Users\Lucas\Documents\FileSync\share', '/home/share/', disabled: true
  end

  config.vm.define :client02 do |client02|
    config.vm.provider "virtualbox" do |vb|
      vb.memory = 256
      vb.cpus = 1
      vb.name = "CLIENT02"
      vb.linked_clone = true
    end
  config.vm.hostname = "CLIENT02"
  config.vm.synced_folder 'C:\Users\Lucas\Documents\FileSync\share', '/home/share/', disabled: true
  end

  config.vm.define :client03 do |client03|
    config.vm.provider "virtualbox" do |vb|
      vb.memory = 256
      vb.cpus = 1
      vb.name = "CLIENT03"
      vb.linked_clone = true
    end
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "CLIENT03"
  config.vm.synced_folder 'C:\Users\Lucas\Documents\FileSync\share', '/home/share/', disabled: true
  end

end